# Generated by Django 4.1 on 2022-08-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='UserRegister',
        ),
    ]
